name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S tests -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Engine
      run: cmake --build build --config Release

    - name: Run Core Integration Tests
      run: ctest --test-dir build --output-on-failure
